# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='pass_word',
        ),
        migrations.AddField(
            model_name='tutor',
            name='avg_review_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tutor',
            name='hourly_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='family_name',
            field=models.CharField(default='NULL', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='given_name',
            field=models.CharField(default='NULL', max_length=30),
        ),
    ]
