# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_auto_20171029_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='avg_review_score',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='course_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='short_profile',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='subjects_tags',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='university',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
