# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-29 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_auto_20171029_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='contact_num',
        ),
        migrations.AddField(
            model_name='student',
            name='interests',
            field=models.CharField(default='', max_length=20),
        ),
    ]
