# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-29 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_auto_20171029_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='review_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.Review'),
        ),
        migrations.AlterField(
            model_name='session',
            name='stu_username',
            field=models.CharField(blank=True, default='NULL', max_length=20),
        ),
    ]
