# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-29 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0006_auto_20171029_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='review_id',
        ),
        migrations.AddField(
            model_name='review',
            name='session_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tutorials.Session'),
        ),
    ]
